default_context:
  project_name: 'nextjs-fastapi-boilerplate'
  project_slug: 'nextjs-fastapi-boilerplate'
  domain_main: 'nextjs-fastapi-boilerplate.com'
  domain_staging: 'stag.nextjs-fastapi-boilerplate.com'
  domain_base_api_url: 'http://nextjs-fastapi-boilerplate.com/api/v1'
  domain_base_ws_url: 'ws://nextjs-fastapi-boilerplate.com/api/v1'
  docker_swarm_stack_name_main: 'nextjs-fastapi-boilerplate-com'
  docker_swarm_stack_name_staging: 'stag-nextjs-fastapi-boilerplate-com'
  secret_key: 'changethis'
  first_superuser: 'admin@nextjs-fastapi-boilerplate.com'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.nextjs-fastapi-boilerplate.com", "https://stag.nextjs-fastapi-boilerplate.com", "https://nextjs-fastapi-boilerplate.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_tls: 'True'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@nextjs-fastapi-boilerplate.com'
  smtp_emails_from_name: 'Symona Adaro'
  smtp_emails_to_email: 'info@nextjs-fastapi-boilerplate.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@nextjs-fastapi-boilerplate.com'
  pgadmin_default_user_password: 'changethis'
  neo4j_password: 'changethis'
  traefik_constraint_tag: 'nextjs-fastapi-boilerplate.com'
  traefik_constraint_tag_staging: 'stag.nextjs-fastapi-boilerplate.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/**/*.html, frontend/**/*.jsx, frontend/.next/*, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
